/**
 * AI Content Calendar Generator — Type Definitions
 * Fasa 3.8 (Task 3-H)
 *
 * Defines the shape of weekly content calendars generated by AI,
 * aligned with the Malaysian market (Shopee, TikTok, Lazada, MYT timezone).
 */

// ─── Primitive Aliases ────────────────────────────────────────────────────────

/** Days of a week (Monday-first, the Malaysian/Southeast Asia convention). */
export type DayOfWeek = 'Mon' | 'Tue' | 'Wed' | 'Thu' | 'Fri' | 'Sat' | 'Sun'

/** Supported posting platforms for the calendar. */
export type CalendarPlatform = 'shopee' | 'tiktok' | 'lazada'

/** Content niches the AI can plan around. */
export type CalendarNiche =
  | 'beauty'
  | 'tech'
  | 'fashion'
  | 'home'
  | 'food'
  | 'mixed'

/** Voice/tone used for the generated content briefs. */
export type CalendarTone = 'casual' | 'professional' | 'hype' | 'educational'

/** Algorithmic origin of the calendar data — always included in API responses. */
export type CalendarSource = 'ai' | 'mock'

/** Canonical time slots used by the calendar grid. */
export type TimeSlot = 'morning' | 'lunch' | 'evening' | 'peak' | 'night'

/** ISO date (YYYY-MM-DD) representing the Monday of a target week. */
export type WeekStartISO = string

// ─── Seasonal Events ──────────────────────────────────────────────────────────

/**
 * A Malaysian seasonal event (sales, holidays, cultural festivals)
 * that influences content planning and commission rates.
 */
export interface SeasonalEvent {
  /** Stable identifier, e.g. `1111-sale`. */
  id: string
  /** Display name, e.g. `11.11 Mega Sale`. */
  name: string
  /** Emoji used in banners and badges. */
  emoji: string
  /** Short human description of the event. */
  description: string
  /** ISO month (1-12) and day of the event peak. */
  month: number
  day: number
  /**
   * Lead-in days before the event where content should ramp up.
   * Defaults to 7 if omitted.
   */
  leadInDays?: number
  /** Multiplier applied to base commission during this event (1.0 = normal). */
  commissionMultiplier: number
  /** Niches that see the biggest lift during this event. */
  recommendedNiches: CalendarNiche[]
  /** Content theme suggestions used by the AI prompt builder. */
  contentThemes: string[]
  /** Hashtags the AI should sprinkle into briefs during this event. */
  hashtags: string[]
}

// ─── Calendar Entries ─────────────────────────────────────────────────────────

/**
 * Predicted performance breakdown for a calendar entry.
 * Scores are 0-100, with `overall` being the canonical `predictedScore`.
 */
export interface PredictedScoreBreakdown {
  /** Engagement potential (likes, comments, shares). */
  engagement: number
  /** Conversion potential (clicks → add-to-cart → purchase). */
  conversion: number
  /** Viral/reach potential (algorithm push, FYP). */
  virality: number
  /** Seasonal alignment boost (sale/holiday relevance). */
  seasonal: number
  /** Canonical aggregate score, 0-100. */
  overall: number
}

/**
 * A single scheduled content entry inside a weekly calendar.
 * One entry = one platform + one day + one time slot.
 */
export interface CalendarEntry {
  /** Unique ID within the calendar (e.g. `entry-mon-peak-0`). */
  id: string
  /** Day of the week (Mon-Sun). */
  day: DayOfWeek
  /** Time slot. */
  timeSlot: TimeSlot
  /** Hour in 24h MYT (e.g. 8, 12, 18, 20, 22). */
  hour: number
  /** Minute (usually 0 or 30). */
  minute: number
  /** Display label, e.g. `8:00 PM`. */
  timeLabel: string
  /** Target platform for this entry. */
  platform: CalendarPlatform
  /** Optional fallback: also post to these platforms. */
  secondaryPlatforms?: CalendarPlatform[]
  /** Product name / hero item featured in this post. */
  product: string
  /** Short content brief — the angle/hook the AI suggests. */
  contentBrief: string
  /** Hashtags to use (mix of niche + seasonal + disclosure). */
  hashtags: string[]
  /** Predicted performance breakdown. */
  predictedScore: PredictedScoreBreakdown
  /** Linked seasonal event ID, if this entry is themed around one. */
  seasonalEventId?: string
  /** Free-form note shown in the detail dialog. */
  note?: string
  /** True if the user has converted this entry into a scheduled auto-post. */
  scheduled?: boolean
}

// ─── Calendar Week & Calendar ─────────────────────────────────────────────────

/**
 * A weekly slice of a calendar: the entries for a 7-day window
 * starting from `weekStartDate`.
 */
export interface CalendarWeek {
  /** ISO date (YYYY-MM-DD) of the Monday starting this week. */
  weekStartDate: WeekStartISO
  /** ISO date (YYYY-MM-DD) of the Sunday ending this week. */
  weekEndDate: string
  /** Human label, e.g. `Week of 11 Nov — 17 Nov 2024`. */
  label: string
  /** All entries scheduled within this week. */
  entries: CalendarEntry[]
  /** Seasonal events active or upcoming during this week. */
  seasonalEvents: SeasonalEvent[]
}

/**
 * User preferences that shape calendar generation.
 */
export interface CalendarPreferences {
  /** Primary niche the affiliate focuses on. */
  niche: CalendarNiche
  /** Platforms to schedule content for. */
  platforms: CalendarPlatform[]
  /** Target posts per day (1-5). */
  postsPerDay: number
  /** Voice/tone for the generated briefs. */
  tone: CalendarTone
  /** Whether to auto-boost entries during seasonal events. */
  seasonalBoost: boolean
  /** Optional list of product names/URLs the user wants featured. */
  featuredProducts?: string[]
}

/**
 * A complete content calendar document, returned by the API.
 * Always carries a `source` field so the frontend knows whether
 * the data came from the AI or a mock fallback.
 */
export interface ContentCalendar {
  /** Unique ID for this calendar document. */
  id: string
  /** ISO date of the Monday starting the calendar week. */
  weekStartDate: WeekStartISO
  /** ISO date of the Sunday ending the calendar week. */
  weekEndDate: string
  /** Human-readable label. */
  label: string
  /** The entries generated for this week (7-14 entries). */
  entries: CalendarEntry[]
  /** Seasonal events considered when generating this calendar. */
  seasonalEvents: SeasonalEvent[]
  /** Preferences used to generate this calendar. */
  preferences: CalendarPreferences
  /** Algorithmic origin — always present. */
  source: CalendarSource
  /** ISO timestamp of generation. */
  generatedAt: string
}

// ─── API Request/Response Shapes ──────────────────────────────────────────────

/** POST /api/ai/calendar body. */
export interface GenerateCalendarRequest {
  /** Optional explicit week start (ISO date). Defaults to next Monday. */
  weekStartDate?: WeekStartISO
  /** Primary niche. */
  niche: CalendarNiche
  /** Target platforms. */
  platforms: CalendarPlatform[]
  /** User preferences. */
  preferences: CalendarPreferences
}

/** POST /api/ai/calendar response. */
export interface GenerateCalendarResponse {
  calendar: ContentCalendar
  source: CalendarSource
}

/** POST /api/ai/calendar/schedule body. */
export interface ScheduleCalendarRequest {
  /** ID of the calendar document these entries belong to. */
  calendarId: string
  /** Specific entry IDs to convert. If omitted, schedules ALL entries. */
  entryIds?: string[]
  /** Week start date the entries belong to (used to resolve absolute dates). */
  weekStartDate: WeekStartISO
}

/** Result of scheduling a single entry. */
export interface ScheduleCalendarItemResult {
  entryId: string
  /** ID of the created ScheduledPost row, or null on failure. */
  scheduledPostId: string | null
  /** ISO datetime the post is scheduled for. */
  scheduledAt: string
  platform: CalendarPlatform
  success: boolean
  error?: string
}

/** POST /api/ai/calendar/schedule response. */
export interface ScheduleCalendarResponse {
  calendarId: string
  scheduled: number
  failed: number
  results: ScheduleCalendarItemResult[]
  source: CalendarSource
}

// ─── Time Slot Metadata ───────────────────────────────────────────────────────

/** Static metadata for the five canonical time slots. */
export interface TimeSlotMeta {
  id: TimeSlot
  label: string
  hour: number
  minute: number
  /** Short hint shown in the UI. */
  hint: string
  /** Relative weight for posting frequency (peak gets more entries). */
  weight: number
}

export const TIME_SLOTS: TimeSlotMeta[] = [
  { id: 'morning', label: 'Morning', hour: 8, minute: 0, hint: '8:00 AM — commute / breakfast scroll', weight: 0.8 },
  { id: 'lunch',   label: 'Lunch',   hour: 12, minute: 0, hint: '12:00 PM — lunch break deals', weight: 1.0 },
  { id: 'evening', label: 'Evening', hour: 18, minute: 0, hint: '6:00 PM — post-work browse', weight: 1.1 },
  { id: 'peak',    label: 'Peak',    hour: 20, minute: 0, hint: '8:00 PM — golden hour, highest engagement', weight: 1.4 },
  { id: 'night',   label: 'Night',   hour: 22, minute: 0, hint: '10:00 PM — late-night shoppers', weight: 0.7 },
]

export const DAYS_OF_WEEK: DayOfWeek[] = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

export const NICHE_LABELS: Record<CalendarNiche, string> = {
  beauty: 'Beauty',
  tech: 'Tech',
  fashion: 'Fashion',
  home: 'Home',
  food: 'Food',
  mixed: 'Mixed',
}

export const TONE_LABELS: Record<CalendarTone, string> = {
  casual: 'Casual',
  professional: 'Professional',
  hype: 'Hype',
  educational: 'Educational',
}

export const PLATFORM_LABELS: Record<CalendarPlatform, string> = {
  shopee: 'Shopee',
  tiktok: 'TikTok',
  lazada: 'Lazada',
}
